name: Atualizar Torneios Diários

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia à meia-noite UTC
  workflow_dispatch: # Permite execução manual

permissions:
  contents: write # Permite que o workflow faça push no repositório

jobs:
  update-tournaments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Executar Script Python
        run: python generate_tournaments.py

      - name: Verificar Arquivo Gerado
        run: |
          echo "Conteúdo do diretório:"
          ls -la
          echo "Conteúdo do index.html:"
          cat index.html || echo "Arquivo index.html não encontrado"

      - name: Enviar Arquivo via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/baixarjogos/lidraughts/torneios/puxa-torneios-diariamente/
          local-dir: ./
          exclude: |
            **/*
            !index.html
          protocol: ftp
          timeout: 30000
          log-level: verbose
          state-name: ""

      - name: Commit e Push Alterações
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Atualizar index.html com novos torneios" || echo "Sem alterações para commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
